apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pulse-app-alerts
  labels:
    release: monitor
spec:
  groups:
  - name: pulse-app.rules
    rules:
    - alert: PulseAppDown
      expr: up{job="pulse-app-service"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Pulse App is down"
        description: "The service in namespace pulse-prod has not responded for over 1 minute."