apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pulse-app-monitor
  labels:
    release: monitor
spec:
  # Указываем Prometheus искать в неймспейсе pulse-prod
  namespaceSelector:
    matchNames:
      - pulse-prod
  selector:
    matchLabels:
      app: pulse-app
  endpoints:
  - port: http-backend
    path: /metrics