apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pulse-app-monitor
  labels:
    release: monitor # Этот лейбл важен для связи с вашим Helm-релизом Prometheus
spec:
  namespaceSelector: # КРИТИЧНО: Разрешаем поиск в неймспейсе приложения
    matchNames:
      - pulse-prod
  selector:
    matchLabels:
      app: pulse-app
  endpoints:
  - port: http-backend
    path: /metrics