replicaCount: 1

backend:
  image: ozharkov/pulse-backend:e5a7a142975cae0c9f2c49eda8d37243583a7599
  port: 8000

frontend:
  image: ozharkov/pulse-frontend:e5a7a142975cae0c9f2c49eda8d37243583a7599
  port: 80

database:
  user: "admin"
  existingSecretName: "pulse-db-secret"
  passwordKey: "password"
  name: "pulsedb"
  storageSize: 1Gi

prometheus:
  enabled: true
  image: prom/prometheus:v2.53.1
  port: 9090
  retention: 7d
  storageSize: 2Gi

grafana:
  enabled: true
  image: grafana/grafana:11.1.0
  port: 3000
  storageSize: 2Gi
  adminUser: admin
  existingSecretName: grafana-admin-secret
  adminPasswordKey: password

nodeExporter:
  enabled: true
  image: quay.io/prometheus/node-exporter:v1.8.2
  port: 9100