replicaCount: 1

backend:
  image: ozharkov/pulse-backend
  port: 8000

frontend:
  image: ozharkov/pulse-frontend
  port: 80

database:
  user: "admin"
  existingSecretName: "pulse-db-secret"
  passwordKey: "password"
  name: "pulsedb"
  storageSize: 1Gi