replicaCount: 1

backend:
  image: ozharkov/pulse-backend:f28252c5c775d05524a00b196e7f718fa110b9bc
  port: 8000
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

frontend:
  image: ozharkov/pulse-frontend:f28252c5c775d05524a00b196e7f718fa110b9bc
  port: 80
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

database:
  user: "admin"
  existingSecretName: "pulse-db-secret"
  passwordKey: "password"
  name: "pulsedb"
  storageSize: 1Gi

prometheus:
  enabled: true
  image: prom/prometheus:v2.53.1
  port: 9090
  retention: 7d
  storageSize: 2Gi

grafana:
  enabled: true
  image: grafana/grafana:11.1.0
  port: 3000
  storageSize: 2Gi
  adminUser: admin
  existingSecretName: grafana-admin-secret
  adminPasswordKey: password

nodeExporter:
  enabled: true
  image: quay.io/prometheus/node-exporter:v1.8.2
  port: 9100

autoscaling:
  enabled: true
  mode: custom
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80
  targetRequestsPerSecondPerPod: "5"

prometheusAdapter:
  enabled: true
  image: registry.k8s.io/prometheus-adapter/prometheus-adapter:v0.12.0
  port: 6443