name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Images
        run: |
          docker build -t pulse-backend ./backend
          docker build -t pulse-frontend ./frontend
